type TAUser {
  id: String!
  phone: String
}

input TAVerifyInput {
  phone: String!
  code: String!
}

type TAUserResp implements TinyAuthResponse {
  status: String!
  success: Boolean!
  message: String!
  auth: String
}

extend type Query {
  getMe: TAUser
}

extend type Mutation {
  sendVerification(phone: String!): TAUserResp
  verifyUser(verification: TAVerifyInput): TAUserResp
}
