type TAUser {
  id: String!
  phone: String
}

input TAVerifyInput {
  phone: String!
  code: String!
}

type TAUserResp implements TinyAuthResponse {
  status: String!
  success: Boolean!
  message: String!
  auth: String
}

extend type Query {
  getMe: TAUser
}

extend type Mutation {
  # Phone number to send verification to and message to send to user ex. Your code is _
  sendVerification(phone: String!, message: String): TAUserResp
  verifyUser(verification: TAVerifyInput): TAUserResp
}
